sudo : required
services:
  - docker

before_install:
  - docker build -t vishalchakravarthi/docker-react -f Dockerfile.dev

script:
  - docker run vishalchakravarthi/docker-react npm run test -- --coverage     